import type {
  AppNotification,
  Booking,
  Category,
  ConditionEvidence,
  DeliveryOpportunity,
  DriverDashboard,
  DriverProfile,
  DriverRoute,
  Escrow,
  Requirement,
  Resource,
  ResourceRequest,
  SearchProduct,
  UserDashboard,
  UserProfile,
} from "./types";

export const MOCK_USER: UserProfile = {
  userId: "usr_grand_hyatt_bkc",
  name: "Niranjan Deshmukh",
  businessName: "Grand Hyatt Mumbai & Residences",
  contactName: "Niranjan Deshmukh",
  email: "operations@grandhyatt.mumbai.demo",
  phone: "+91 98201 98765",
  businessType: "hotel",
  address: "Bandra Kurla Complex, Santacruz East, Mumbai, Maharashtra 400055",
  rating: 4.92,
  totalRatings: 46,
  reviewCount: 46,
  location: {
    lat: 19.0728,
    lng: 72.855,
    address: "Bandra Kurla Complex, Mumbai 400055",
  },
  createdAt: "2026-08-15T09:00:00Z",
  updatedAt: "2026-09-26T18:30:00Z",
};

export const MOCK_CATEGORIES: Category[] = [
  { id: "furniture", name: "Banquet & Event Furniture", evidenceType: "photo", metric: "units" },
  { id: "catering_equipment", name: "Commercial Kitchen & Catering", evidenceType: "photo", metric: "units" },
  { id: "audio_visual", name: "Audio-Visual & Lighting Systems", evidenceType: "video", metric: "units" },
  { id: "tableware", name: "Fine Tableware & Cutlery Sets", evidenceType: "photo", metric: "units" },
  { id: "refrigeration", name: "Cold Storage & Mobile Refrigeration", evidenceType: "photo", metric: "units" },
  { id: "event_space", name: "Ballrooms & Outdoor Event Spaces", evidenceType: "video", metric: "sqm" },
  { id: "linens", name: "Luxury Linens & Draping", evidenceType: "photo", metric: "units" },
  { id: "vehicles", name: "Refrigerated Transport Vans", evidenceType: "photo", metric: "units" },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    resourceId: "res_chairs_01",
    userId: "usr_grand_hyatt_bkc",
    name: "Luxury Gold Chiavari Banquet Chairs (with Ivory Cushions)",
    category: "furniture",
    description: "Stackable high-grade beechwood banquet chairs with stain-resistant cushions. Ideal for weddings, galas, and VIP corporate summits.",
    quantity: 250,
    availableQuantity: 180,
    price: 150,
    pricingUnit: "per_day",
    status: "active",
    images: [
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80",
    ],
    location: {
      address: "Bandra Kurla Complex, Mumbai",
      lat: 19.0728,
      lng: 72.855,
    },
    createdAt: "2026-09-20T10:00:00Z",
    updatedAt: "2026-09-26T12:00:00Z",
  },
  {
    resourceId: "res_tables_02",
    userId: "usr_taj_colaba",
    name: "Round Banquet Dining Tables (6ft, seats 10, with Damask Tablecloth)",
    category: "furniture",
    description: "Solid hardwood folding banqueting round tables with reinforced steel legs and premium linen.",
    quantity: 35,
    availableQuantity: 28,
    price: 750,
    pricingUnit: "per_day",
    status: "active",
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    ],
    location: {
      address: "Apollo Bunder, Colaba, Mumbai",
      lat: 18.9217,
      lng: 72.8332,
    },
    createdAt: "2026-09-22T08:00:00Z",
    updatedAt: "2026-09-26T14:00:00Z",
  },
  {
    resourceId: "res_chafing_03",
    userId: "usr_trident_nariman",
    name: "Stainless Steel Roll-Top Chafing Dishes (9L Induction Compatible)",
    category: "catering_equipment",
    description: "Premium mirror-polished food grade stainless steel chafing dishes with hydraulic soft-closing lids.",
    quantity: 45,
    availableQuantity: 36,
    price: 350,
    pricingUnit: "per_day",
    status: "active",
    images: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    ],
    location: {
      address: "Nariman Point, Marine Drive, Mumbai",
      lat: 18.9272,
      lng: 72.8211,
    },
    createdAt: "2026-09-21T11:30:00Z",
    updatedAt: "2026-09-25T16:00:00Z",
  },
  {
    resourceId: "res_projector_04",
    userId: "usr_jw_juhu",
    name: "Christie 10,000-Lumen 4K Laser Event Projector + 200\" Screen",
    category: "audio_visual",
    description: "High-contrast conference projection package with HDMI distribution, ceiling rig, and calibrated lens.",
    quantity: 3,
    availableQuantity: 2,
    price: 14500,
    pricingUnit: "per_day",
    status: "active",
    images: [
      "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80",
    ],
    location: {
      address: "Juhu Tara Road, Juhu Beach, Mumbai",
      lat: 19.1009,
      lng: 72.8267,
    },
    createdAt: "2026-09-18T09:15:00Z",
    updatedAt: "2026-09-24T18:00:00Z",
  },
  {
    resourceId: "res_combi_05",
    userId: "usr_blue_sea_worli",
    name: "Rational iCombi Pro 20-Grid High-Capacity Commercial Combi Oven",
    category: "catering_equipment",
    description: "Heavy-duty electric combi steamer capable of plating 180 banquet covers per hour. Three-phase power required.",
    quantity: 2,
    availableQuantity: 1,
    price: 16000,
    pricingUnit: "per_day",
    status: "active",
    images: [
      "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80",
    ],
    location: {
      address: "Worli Sea Face, Worli, Mumbai",
      lat: 19.0144,
      lng: 72.8159,
    },
    createdAt: "2026-09-19T14:00:00Z",
    updatedAt: "2026-09-26T11:00:00Z",
  },
  {
    resourceId: "res_chiller_06",
    userId: "usr_itc_maratha",
    name: "Mobile Walk-In Cold Room Trailer (-2°C to +8°C, 12 ft)",
    category: "refrigeration",
    description: "Towable refrigerated storage trailer with quiet on-board backup generator. Keeps seafood, butchery, and pastry pristine.",
    quantity: 3,
    availableQuantity: 2,
    price: 8500,
    pricingUnit: "per_day",
    status: "active",
    images: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80",
    ],
    location: {
      address: "Sahar Airport Road, Andheri East, Mumbai",
      lat: 19.1025,
      lng: 72.8681,
    },
    createdAt: "2026-09-23T15:00:00Z",
    updatedAt: "2026-09-26T17:20:00Z",
  },
];

export const MOCK_SEARCH_PRODUCTS: SearchProduct[] = [
  {
    resourceId: "res_chairs_01",
    name: "Luxury Gold Chiavari Banquet Chairs (with Ivory Cushions)",
    category: "furniture",
    description: "Stackable high-grade beechwood banquet chairs with stain-resistant cushions.",
    quantity: 250,
    availableQuantity: 180,
    price: 150,
    pricingUnit: "per_day",
    status: "active",
    images: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=800&q=80"],
    location: { address: "Bandra Kurla Complex, Mumbai", lat: 19.0728, lng: 72.855 },
    provider: {
      providerId: "usr_grand_hyatt_bkc",
      businessName: "Grand Hyatt Mumbai & Residences",
      rating: 4.92,
      reviewCount: 46,
      location: { address: "Bandra Kurla Complex, Mumbai", lat: 19.0728, lng: 72.855 },
    },
    matchedItem: {
      name: "Banquet Chairs",
      category: "furniture",
      requestedQuantity: 100,
      matchedQuantity: 100,
      metric: "units",
    },
    availableForRequestedPeriod: true,
    availabilityScore: 100,
    distanceKm: 0.8,
    matchScore: 98,
    matchReasons: ["Exact quantity available in stock", "Under 1 km from delivery address", "Top rated 5-star venue"],
  },
  {
    resourceId: "res_tables_02",
    name: "Round Banquet Dining Tables (6ft, seats 10, with Damask Tablecloth)",
    category: "furniture",
    description: "Solid hardwood folding banqueting round tables with reinforced steel legs and premium linen.",
    quantity: 35,
    availableQuantity: 28,
    price: 750,
    pricingUnit: "per_day",
    status: "active",
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80"],
    location: { address: "Apollo Bunder, Colaba, Mumbai", lat: 18.9217, lng: 72.8332 },
    provider: {
      providerId: "usr_taj_colaba",
      businessName: "The Taj Mahal Palace",
      rating: 4.95,
      reviewCount: 82,
      location: { address: "Apollo Bunder, Colaba, Mumbai", lat: 18.9217, lng: 72.8332 },
    },
    matchedItem: {
      name: "Round Tables",
      category: "furniture",
      requestedQuantity: 10,
      matchedQuantity: 10,
      metric: "units",
    },
    availableForRequestedPeriod: true,
    availabilityScore: 95,
    distanceKm: 16.4,
    matchScore: 91,
    matchReasons: ["Includes custom linen", "Matched with active South Mumbai transport route", "Super-host rating"],
  },
  {
    resourceId: "res_chafing_03",
    name: "Stainless Steel Roll-Top Chafing Dishes (9L Induction Compatible)",
    category: "catering_equipment",
    description: "Premium mirror-polished food grade stainless steel chafing dishes with hydraulic soft-closing lids.",
    quantity: 45,
    availableQuantity: 36,
    price: 350,
    pricingUnit: "per_day",
    status: "active",
    images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"],
    location: { address: "Nariman Point, Marine Drive, Mumbai", lat: 18.9272, lng: 72.8211 },
    provider: {
      providerId: "usr_trident_nariman",
      businessName: "Trident Hotel Nariman Point",
      rating: 4.88,
      reviewCount: 39,
      location: { address: "Nariman Point, Marine Drive, Mumbai", lat: 18.9272, lng: 72.8211 },
    },
    matchedItem: {
      name: "Chafing Dishes",
      category: "catering_equipment",
      requestedQuantity: 20,
      matchedQuantity: 20,
      metric: "units",
    },
    availableForRequestedPeriod: true,
    availabilityScore: 90,
    distanceKm: 15.2,
    matchScore: 89,
    matchReasons: ["Hygienically sanitized between events", "Compatible with hotel-grade induction units"],
  },
];

export const MOCK_REQUESTS: ResourceRequest[] = [
  {
    requestId: "req_trident_01",
    seekerId: "usr_trident_nariman",
    providerId: "usr_grand_hyatt_bkc",
    resourceId: "res_chairs_01",
    requestedQuantity: 80,
    offeredPrice: 11200,
    counterPrice: 12000,
    counterNotes: "We can do ₹150/unit including ivory cushions and stacking covers.",
    status: "countered",
    message: "Seeking 80 gold Chiavari chairs for our rooftop banquet reception.",
    createdAt: "2026-09-26T15:20:00Z",
    updatedAt: "2026-09-26T17:45:00Z",
    resource: MOCK_RESOURCES[0],
    seeker: {
      userId: "usr_trident_nariman",
      businessName: "Trident Hotel Nariman Point",
      contactName: "Vikram Malhotra",
      phone: "+91 98200 11223",
      rating: 4.88,
    },
  },
  {
    requestId: "req_bluesea_02",
    seekerId: "usr_blue_sea_worli",
    providerId: "usr_grand_hyatt_bkc",
    resourceId: "res_chairs_01",
    requestedQuantity: 50,
    offeredPrice: 7500,
    status: "pending",
    message: "Need 50 chairs for evening cocktail lounge setup. Can pick up ourselves or arrange pooling.",
    createdAt: "2026-09-26T19:10:00Z",
    updatedAt: "2026-09-26T19:10:00Z",
    resource: MOCK_RESOURCES[0],
    seeker: {
      userId: "usr_blue_sea_worli",
      businessName: "Blue Sea Banquets Worli",
      contactName: "Pooja Mehta",
      phone: "+91 98333 44556",
      rating: 4.75,
    },
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    bookingId: "bk_94821a_hyatt_taj",
    requestId: "req_taj_prior_01",
    seekerId: "usr_taj_colaba",
    providerId: "usr_grand_hyatt_bkc",
    resourceId: "res_chairs_01",
    quantity: 100,
    resourceAmount: 15000,
    deliveryAmount: 1200,
    depositAmount: 2500,
    totalAmount: 16200,
    status: "confirmed",
    driverId: "drv_ramesh_pawar",
    pickupDate: "2026-09-27T14:00:00Z",
    deliveryDate: "2026-09-28T22:00:00Z",
    createdAt: "2026-09-26T11:00:00Z",
  },
  {
    bookingId: "bk_81034b_jw_hyatt",
    requestId: "req_jw_prior_02",
    seekerId: "usr_grand_hyatt_bkc",
    providerId: "usr_jw_juhu",
    resourceId: "res_projector_04",
    quantity: 1,
    resourceAmount: 14500,
    deliveryAmount: 1100,
    depositAmount: 3000,
    totalAmount: 15600,
    status: "in_transit",
    driverId: "drv_ramesh_pawar",
    pickupDate: "2026-09-27T10:00:00Z",
    deliveryDate: "2026-09-27T23:00:00Z",
    createdAt: "2026-09-25T14:00:00Z",
  },
];

export const MOCK_ESCROW: Record<string, Escrow> = {
  bk_94821a_hyatt_taj: {
    escrowId: "esc_94821",
    bookingId: "bk_94821a_hyatt_taj",
    totalAmount: 15000,
    providerPayout: 13500,
    driverPayout: 1200,
    platformFee: 300,
    damageDeposit: 2500,
    status: "funded",
    paymentReference: "PAY_HACK_MUM_94821",
    fundedAt: "2026-09-26T16:30:00Z",
  },
  bk_81034b_jw_hyatt: {
    escrowId: "esc_81034",
    bookingId: "bk_81034b_jw_hyatt",
    totalAmount: 14500,
    providerPayout: 13050,
    driverPayout: 1100,
    platformFee: 350,
    damageDeposit: 3000,
    status: "funded",
    paymentReference: "PAY_HACK_MUM_81034",
    fundedAt: "2026-09-25T16:00:00Z",
  },
};

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    notificationId: "notif_01",
    userId: "usr_grand_hyatt_bkc",
    type: "request_received",
    title: "New rental request received",
    message: "Blue Sea Banquets requested 50 × Gold Chiavari Chairs for ₹7,500.",
    read: false,
    link: "/dashboard/requests",
    createdAt: "2026-09-26T19:10:00Z",
  },
  {
    notificationId: "notif_02",
    userId: "usr_grand_hyatt_bkc",
    type: "escrow_funded",
    title: "Payment secured in Escrow",
    message: "₹15,000 for Booking #BK-94821 has been locked in safe escrow.",
    read: false,
    link: "/dashboard/bookings/bk_94821a_hyatt_taj",
    createdAt: "2026-09-26T16:30:00Z",
  },
  {
    notificationId: "notif_03",
    userId: "usr_grand_hyatt_bkc",
    type: "driver_matched",
    title: "Shared-Route Logistics Matched",
    message: "Driver Ramesh Pawar (Bolero Maxi Truck) matched your Colaba transport corridor.",
    read: true,
    link: "/dashboard/bookings/bk_94821a_hyatt_taj",
    createdAt: "2026-09-26T14:15:00Z",
  },
];

export const MOCK_USER_DASHBOARD: UserDashboard = {
  activeResources: 6,
  activeBookings: 2,
  completedBookings: 24,
  pendingRequests: 2,
  totalEarnings: 184500,
};

export const MOCK_DRIVER: DriverProfile = {
  driverId: "drv_ramesh_pawar",
  name: "Ramesh Pawar",
  phone: "+91 97690 12345",
  vehicleType: "Tata Ace Gold",
  vehicleNumber: "MH-02-DN-4821",
  capacity: 50,
  verificationStatus: "verified",
  rating: 4.88,
  totalTrips: 112,
  createdAt: "2026-08-10T10:00:00Z",
};

export const MOCK_DRIVER_ROUTES: DriverRoute[] = [
  {
    routeId: "route_mumbai_spine_01",
    driverId: "drv_ramesh_pawar",
    startLocation: {
      address: "BKC Transport Hub, Bandra East, Mumbai",
      lat: 19.065,
      lng: 72.862,
    },
    endLocation: {
      address: "Colaba Bus Depot, Shahid Bhagat Singh Road, Colaba",
      lat: 18.9167,
      lng: 72.828,
    },
    stops: [
      { address: "Worli Sea Face Junction", lat: 19.0144, lng: 72.8159 },
      { address: "Mahalaxmi Race Course / Lower Parel", lat: 18.9822, lng: 72.8242 },
    ],
    travelDate: "2026-09-28",
    departureTime: "10:00",
    estimatedArrival: "12:45",
    totalCapacity: 50,
    availableCapacity: 45,
    status: "active",
    pricePerKm: 35,
    createdAt: "2026-09-26T10:00:00Z",
  },
];

export const MOCK_DRIVER_DASHBOARD: DriverDashboard = {
  activeRoutes: 1,
  activeDeliveries: 1,
  completedDeliveries: 42,
  totalEarnings: 56400,
  pendingPayments: 2300,
  matchedRequests: 3,
};
